### ISSUE TITLE
simple guide

### ISSUE THREAD

**Issue by chemix** [JanTvrdik/NetteDocumentationConverter#1]
Hi Honza, 
do You have in plan add some simple guide how to use it? Or exists other repository with code that use this package?

**Comment by JanTvrdik** [comment]
There is no guide, see [PageRenderer](https://github.com/JanTvrdik/NetteDocumentationEditor/blob/9d18f7ca97760d2c71df9a96d6b62b098d95eaf4/app/view/PageRenderer/PageRenderer.php) class for usage example (live demo at http://nette.merxes.cz/editor/)

**Comment by chemix** [comment]
thanks
